# Generated by Django 5.2.10 on 2026-01-12 17:50

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(help_text='Ex: 2024', unique=True)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('year_level', models.IntegerField(choices=[(1, '1º Ano'), (2, '2º Ano'), (3, '3º Ano'), (4, '4º Ano')], verbose_name='Ano Curricular')),
                ('workload', models.IntegerField(help_text='Carga horária em horas')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('enrollment_number', models.CharField(max_length=20, unique=True, verbose_name='Número de Matrícula')),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluation_type', models.CharField(choices=[('TEST', 'Teste'), ('EXAM', 'Exame'), ('WORK', 'Trabalho')], max_length=10)),
                ('value', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)])),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.academicyear')),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='school.discipline')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='school.student')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='FinalGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('final_score', models.DecimalField(decimal_places=2, max_digits=4)),
                ('is_approved', models.BooleanField()),
                ('generated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.academicyear')),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.discipline')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='final_grades', to='school.student')),
            ],
            options={
                'unique_together': {('student', 'discipline', 'academic_year')},
            },
        ),
    ]
